In [1]:
#model = GradientBoostingClassifier(n_estimators=100)

In [12]:
import pandas as pd
import numpy as np
df = pd.read_csv('shuffle.csv')
df.head()

,team1_seed,team2_seed,team1_dis(km),team2_dis(km),team1_pt_school_ncaa,team1_pt_overall_ncaa,team1_pt_school_s16,team1_pt_overall_s16,team1_pt_school_ff,team1_pt_overall_ff,...,team2_stlrate,team2_oppstlrate,team1_adjtempo,team1_adjoe,team1_adjde,team2_adjtempo,team2_adjoe,team2_adjde,team1_outcome,game_id
0,16,16,1076.682624,932.116689,6,6,0,0,0,0,...,0.0778,0.1020,73.8504,99.8665,106.4500,67.7359,98.6102,99.6885,0,2002-1373-1108
1,2,15,969.775258,1058.567916,0,2,0,0,0,0,...,0.1282,0.1076,69.9001,111.4954,93.8770,71.2446,96.8669,99.9263,1,2002-1104-1194
2,14,3,1210.852647,513.529264,0,0,0,0,0,0,...,0.0835,0.0839,64.7948,105.4534,97.6704,72.8207,117.3877,96.9262,0,2002-1112-1364
3,16,1,339.990955,148.384590,3,3,0,0,0,0,...,0.1297,0.0919,67.4639,95.3632,99.9754,75.1685,118.5999,87.7504,0,2002-1181-1457
4,5,12,3007.304604,859.001991,1,1,0,0,0,0,...,0.0922,0.0927,66.5739,109.6136,89.9224,63.3547,108.6231,95.6459,1,2002-1231-1428

In [13]:
game_id = df['game_id'].tolist()
df = df.drop(['game_id'],axis = 1)
df.head()

,team1_seed,team2_seed,team1_dis(km),team2_dis(km),team1_pt_school_ncaa,team1_pt_overall_ncaa,team1_pt_school_s16,team1_pt_overall_s16,team1_pt_school_ff,team1_pt_overall_ff,...,team2_opparate,team2_stlrate,team2_oppstlrate,team1_adjtempo,team1_adjoe,team1_adjde,team2_adjtempo,team2_adjoe,team2_adjde,team1_outcome
0,16,16,1076.682624,932.116689,6,6,0,0,0,0,...,57.8947,0.0778,0.1020,73.8504,99.8665,106.4500,67.7359,98.6102,99.6885,0
1,2,15,969.775258,1058.567916,0,2,0,0,0,0,...,56.3399,0.1282,0.1076,69.9001,111.4954,93.8770,71.2446,96.8669,99.9263,1
2,14,3,1210.852647,513.529264,0,0,0,0,0,0,...,54.8255,0.0835,0.0839,64.7948,105.4534,97.6704,72.8207,117.3877,96.9262,0
3,16,1,339.990955,148.384590,3,3,0,0,0,0,...,49.5516,0.1297,0.0919,67.4639,95.3632,99.9754,75.1685,118.5999,87.7504,0
4,5,12,3007.304604,859.001991,1,1,0,0,0,0,...,51.5702,0.0922,0.0927,66.5739,109.6136,89.9224,63.3547,108.6231,95.6459,1

In [14]:
array = df.values
x = array[:,0:66]
y = array[:,66]
x.shape, y.shape

((1112, 66), (1112,))

In [15]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn import cross_validation
sc = StandardScaler()
x_std = sc.fit_transform(x)
pca = PCA(n_components = 'mle',svd_solver='full')
x_pca = pca.fit_transform(x_std)
x_train_pca, x_test_pca, y_train, y_test = cross_validation.train_test_split(x_pca,y,test_size=0.3,random_state = 42)
x_train_pca.shape,x_test_pca.shape

((778, 65), (334, 65))

In [16]:
param_test1 = {'n_estimators':range(20,81,10)}
gsearch1 = GridSearchCV(estimator = GradientBoostingClassifier(learning_rate=0.1, min_samples_split=300,
                                  min_samples_leaf=20,max_depth=8,max_features='sqrt', subsample=0.8,random_state=10), 
                       param_grid = param_test1, scoring='roc_auc',iid=False,cv=5)
gsearch1.fit(x_train_pca,y_train)
gsearch1.grid_scores_, gsearch1.best_params_, gsearch1.best_score_

C:\Users\AndyZ\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:761: DeprecationWarning: The grid_scores_ attribute was deprecated in version 0.18 in favor of the more elaborate cv_results_ attribute. The grid_scores_ attribute will not be available from 0.20
  DeprecationWarning)

([mean: 0.69867, std: 0.02284, params: {'n_estimators': 20},
  mean: 0.70441, std: 0.03071, params: {'n_estimators': 30},
  mean: 0.71351, std: 0.02296, params: {'n_estimators': 40},
  mean: 0.72144, std: 0.02413, params: {'n_estimators': 50},
  mean: 0.72297, std: 0.02606, params: {'n_estimators': 60},
  mean: 0.72767, std: 0.02057, params: {'n_estimators': 70},
  mean: 0.72847, std: 0.01579, params: {'n_estimators': 80}],
 {'n_estimators': 80},
 0.7284716139977118)

In [17]:
param_test2 = {'max_depth':range(3,14,2), 'min_samples_split':range(100,801,200)}
gsearch2 = GridSearchCV(estimator = GradientBoostingClassifier(learning_rate=0.1, n_estimators=80, min_samples_leaf=20, 
      max_features='sqrt', subsample=0.8, random_state=10), 
   param_grid = param_test2, scoring='roc_auc',iid=False, cv=5)
gsearch2.fit(x_train_pca,y_train)
gsearch2.grid_scores_, gsearch2.best_params_, gsearch2.best_score_

C:\Users\AndyZ\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:761: DeprecationWarning: The grid_scores_ attribute was deprecated in version 0.18 in favor of the more elaborate cv_results_ attribute. The grid_scores_ attribute will not be available from 0.20
  DeprecationWarning)

([mean: 0.72762, std: 0.02377, params: {'max_depth': 3, 'min_samples_split': 100},
  mean: 0.73149, std: 0.01718, params: {'max_depth': 3, 'min_samples_split': 300},
  mean: 0.50000, std: 0.00000, params: {'max_depth': 3, 'min_samples_split': 500},
  mean: 0.50000, std: 0.00000, params: {'max_depth': 3, 'min_samples_split': 700},
  mean: 0.72390, std: 0.01112, params: {'max_depth': 5, 'min_samples_split': 100},
  mean: 0.72814, std: 0.01628, params: {'max_depth': 5, 'min_samples_split': 300},
  mean: 0.50000, std: 0.00000, params: {'max_depth': 5, 'min_samples_split': 500},
  mean: 0.50000, std: 0.00000, params: {'max_depth': 5, 'min_samples_split': 700},
  mean: 0.73404, std: 0.00795, params: {'max_depth': 7, 'min_samples_split': 100},
  mean: 0.72847, std: 0.01579, params: {'max_depth': 7, 'min_samples_split': 300},
  mean: 0.50000, std: 0.00000, params: {'max_depth': 7, 'min_samples_split': 500},
  mean: 0.50000, std: 0.00000, params: {'max_depth': 7, 'min_samples_split': 700},
  mean: 0.71116, std: 0.01333, params: {'max_depth': 9, 'min_samples_split': 100},
  mean: 0.72847, std: 0.01579, params: {'max_depth': 9, 'min_samples_split': 300},
  mean: 0.50000, std: 0.00000, params: {'max_depth': 9, 'min_samples_split': 500},
  mean: 0.50000, std: 0.00000, params: {'max_depth': 9, 'min_samples_split': 700},
  mean: 0.70677, std: 0.01167, params: {'max_depth': 11, 'min_samples_split': 100},
  mean: 0.72847, std: 0.01579, params: {'max_depth': 11, 'min_samples_split': 300},
  mean: 0.50000, std: 0.00000, params: {'max_depth': 11, 'min_samples_split': 500},
  mean: 0.50000, std: 0.00000, params: {'max_depth': 11, 'min_samples_split': 700},
  mean: 0.70773, std: 0.01357, params: {'max_depth': 13, 'min_samples_split': 100},
  mean: 0.72847, std: 0.01579, params: {'max_depth': 13, 'min_samples_split': 300},
  mean: 0.50000, std: 0.00000, params: {'max_depth': 13, 'min_samples_split': 500},
  mean: 0.50000, std: 0.00000, params: {'max_depth': 13, 'min_samples_split': 700}],
 {'max_depth': 7, 'min_samples_split': 100},
 0.7340391367814731)

In [27]:
y_pred = gsearch2.predict(x_pca)
y_predprob = gsearch2.predict_proba(x_pca)[:,1]
print ("Accuracy : %.4g" % metrics.accuracy_score(y, y_pred))
print ("AUC Score (Train): %f" % metrics.roc_auc_score(y, y_predprob))

Accuracy : 0.9074
AUC Score (Train): 0.957836

In [6]:
# from sklearn.ensemble import GradientBoostingClassifier
# from sklearn.model_selection import GridSearchCV
# param_test2 = {'max_depth':range(3,14,2), 'min_samples_split':range(100,801,200)}
# gsearch2 = GridSearchCV(estimator = GradientBoostingClassifier(learning_rate=0.1, n_estimators=80, min_samples_leaf=20, 
#       max_features='sqrt', subsample=0.8, random_state=10), 
#    param_grid = param_test2, scoring='roc_auc',iid=False, cv=5)
# gsearch2.fit(x_pca,y)
# gsearch2.grid_scores_, gsearch2.best_params_, gsearch2.best_score_
# from sklearn import cross_validation, metrics
# y_predprob = gsearch2.predict_proba(x_pca)[:,1]
# y_pred = gsearch2.predict(x_pca)
# a = metrics.accuracy_score(y, y_pred)
# s = metrics.roc_auc_score(y, y_predprob)
# a,s

C:\Users\AndyZ\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:761: DeprecationWarning: The grid_scores_ attribute was deprecated in version 0.18 in favor of the more elaborate cv_results_ attribute. The grid_scores_ attribute will not be available from 0.20
  DeprecationWarning)
C:\Users\AndyZ\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

(0.8138489208633094, 0.9095981416654737)

In [28]:
#è¿”å›žprobability ç¬¬äºŒåˆ—è¡¨ç¤ºè¯¥åœºæ¯”èµ›team1 winçš„æ¦‚çŽ‡
y_prob = gsearch2.predict_proba(x_pca)
y_prob

array([[0.75434271, 0.24565729],
       [0.12597009, 0.87402991],
       [0.56217242, 0.43782758],
       ...,
       [0.3534492 , 0.6465508 ],
       [0.90423095, 0.09576905],
       [0.86729024, 0.13270976]])

In [29]:
df['team1_outcome_pred'] = y_pred[:]
team1_win = []
for lst in y_prob:
    p = lst[1]
    team1_win.append(p)

In [30]:
df['game_id'] = game_id
df['probability'] = team1_win
df.head()

,team1_seed,team2_seed,team1_dis(km),team2_dis(km),team1_pt_school_ncaa,team1_pt_overall_ncaa,team1_pt_school_s16,team1_pt_overall_s16,team1_pt_school_ff,team1_pt_overall_ff,...,team1_adjtempo,team1_adjoe,team1_adjde,team2_adjtempo,team2_adjoe,team2_adjde,team1_outcome,team1_outcome_pred,game_id,probability
0,16,16,1076.682624,932.116689,6,6,0,0,0,0,...,73.8504,99.8665,106.4500,67.7359,98.6102,99.6885,0,0.0,2002-1373-1108,0.245657
1,2,15,969.775258,1058.567916,0,2,0,0,0,0,...,69.9001,111.4954,93.8770,71.2446,96.8669,99.9263,1,1.0,2002-1104-1194,0.874030
2,14,3,1210.852647,513.529264,0,0,0,0,0,0,...,64.7948,105.4534,97.6704,72.8207,117.3877,96.9262,0,0.0,2002-1112-1364,0.437828
3,16,1,339.990955,148.384590,3,3,0,0,0,0,...,67.4639,95.3632,99.9754,75.1685,118.5999,87.7504,0,0.0,2002-1181-1457,0.472804
4,5,12,3007.304604,859.001991,1,1,0,0,0,0,...,66.5739,109.6136,89.9224,63.3547,108.6231,95.6459,1,1.0,2002-1231-1428,0.792460

In [31]:
outcome = df.drop(df.columns[0:68],axis = 1)
outcome

             game_id  probability
0     2002-1373-1108     0.245657
1     2002-1104-1194     0.874030
2     2002-1112-1364     0.437828
3     2002-1181-1457     0.472804
4     2002-1231-1428     0.792460
5     2002-1242-1221     0.141013
6     2002-1245-1329     0.507544
7     2002-1246-1434     0.848182
8     2002-1281-1274     0.615303
9     2002-1323-1150     0.684072
10    2002-1326-1172     0.676475
11    2002-1332-1285     0.841543
12    2002-1390-1443     0.615327
13    2002-1409-1266     0.283837
14    2002-1423-1425     0.188667
15    2002-1448-1337     0.246159
16    2002-1461-1211     0.408721
17    2002-1143-1335     0.166516
18    2002-1153-1131     0.049916
19    2002-1163-1214     0.066609
20    2002-1166-1196     0.491160
21    2002-1208-1293     0.211749
22    2002-1228-1361     0.879511
23    2002-1268-1373     0.150480
24    2002-1280-1270     0.841547
25    2002-1301-1277     0.677436
26    2002-1328-1227     0.056751
27    2002-1338-1148     0.883061
28    2002-1356-1403     0.473266
29    2002-1400-1130     0.495118
...              ...          ...
1082  2018-1242-1371     0.056649
1083  2018-1181-1348     0.131356
1084  2018-1211-1326     0.275148
1085  2018-1260-1397     0.407087
1086  2018-1276-1222     0.724907
1087  2018-1403-1196     0.347088
1088  2018-1246-1138     0.818115
1089  2018-1345-1139     0.193183
1090  2018-1452-1267     0.848471
1091  2018-1393-1277     0.175221
1092  2018-1155-1120     0.758272
1093  2018-1243-1420     0.806669
1094  2018-1305-1153     0.461090
1095  2018-1199-1462     0.265867
1096  2018-1401-1314     0.339548
1097  2018-1243-1246     0.422618
1098  2018-1260-1305     0.719007
1099  2018-1199-1211     0.590746
1100  2018-1276-1401     0.119008
1101  2018-1437-1452     0.671023
1102  2018-1403-1345     0.217343
1103  2018-1242-1155     0.106744
1104  2018-1181-1393     0.839250
1105  2018-1437-1403     0.757118
1106  2018-1242-1181     0.689135
1107  2018-1260-1243     0.416375
1108  2018-1276-1199     0.110576
1109  2018-1437-1242     0.646551
1110  2018-1276-1260     0.095769
1111  2018-1437-1276     0.132710

[1112 rows x 2 columns]

In [20]:
outcome.to_csv('result_GBC.csv')

In [32]:
from sklearn.metrics import log_loss
log_loss(y, y_prob)

0.3345023258085286